# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nymdesign.portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(upload_to=nymdesign.portfolio.models.get_project_cat_strip_path)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(upload_to=nymdesign.portfolio.models.get_project_hm_strip_path)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=1)),
                ('band_color', models.CharField(help_text=b'hex color such as "#006699"', max_length=10)),
                ('project_bg_color', models.CharField(help_text=b'hex color such as "#006699"', max_length=10, verbose_name=b'project title background color')),
                ('logo_name', models.CharField(help_text=b'logo file name (not the path) e.g. "logo_web.gif"', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text=b'optional')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=False)),
                ('is_showcase_item', models.BooleanField(default=True)),
                ('project_url', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, help_text=b'auto-filled on save')),
                ('date_text', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(verbose_name=b'date published')),
                ('description', models.TextField(blank=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Client')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.MediaType')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='_project_related_projects_+', to='portfolio.Project')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('regular', models.ImageField(height_field=b'iheight', max_length=255, upload_to=nymdesign.portfolio.models.get_project_image_regular_path, width_field=b'iwidth')),
                ('iwidth', models.IntegerField(default=-1, help_text=b'auto-filled on save')),
                ('iheight', models.IntegerField(default=-1, help_text=b'auto-filled on save')),
                ('sort_order', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project')),
            ],
            options={
                'ordering': ['project', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.ProjectTag'),
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
        migrations.AddField(
            model_name='categorypageimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
